[project]
name = "sheet2ical"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easygui>=0.98.3",
    "icalendar>=6.1.0",
    "openpyxl>=3.1.5",
]
